import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { readFile,readdir } from 'node:fs/promises';
import { DEMO_USERS } from '../src/lib/types';
import type { Snapshot } from '../src/components/workspace';
let db:PGlite;
const student=DEMO_USERS.student,supervisor=DEMO_USERS.supervisor,admin=DEMO_USERS.admin;
const org='20000000-0000-4000-8000-000000000001',challenge='40000000-0000-4000-8000-000000000001',skill='30000000-0000-4000-8000-000000000001';
const fixture={organization_id:org,title:'Experiencia de prueba',description:'Trabajo aplicado documentado',responsibilities:'Analizar procesos',deliverables:'Reporte técnico',start_date:'2026-09-01',end_date:'2026-09-20',hours:16,skill_ids:[skill]};
async function sql<T=Record<string,unknown>>(actor:string|null,query:string,params:unknown[]=[]) {return db.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[actor||'']);await tx.exec(actor?'set local role authenticated':'set local role anon');return (await tx.query<T>(query,params)).rows;});}
async function action(actor:string,name:string,payload:Record<string,unknown>){return (await sql<{r:{id:string}}>(actor,'select nexus_action($1,$2::jsonb) as r',[name,JSON.stringify(payload)]))[0].r;}
async function snapshot(actor=student){return (await sql<{r:Snapshot}>(actor,'select nexus_snapshot() as r'))[0].r;}
async function makePending(){const {id}=await action(student,'create_experience',fixture);await action(student,'add_evidence',{experience_id:id,title:'Evidencia de prueba',description:'Reporte de ejemplo',url:'https://example.com/report',kind:'document',is_public:true});await action(student,'request_validation',{experience_id:id});return id;}
beforeAll(async()=>{db=new PGlite();await db.exec(await readFile('supabase/demo-bootstrap.sql','utf8'));await db.exec("create table public.external_app(value text); grant select on public.external_app to anon; alter default privileges in schema public grant all on tables to anon,authenticated; alter default privileges in schema public grant execute on functions to anon,authenticated;");for(const file of (await readdir('supabase/migrations')).filter(x=>x.endsWith('.sql')).sort())await db.exec(await readFile('supabase/migrations/'+file,'utf8'));await db.exec(await readFile('supabase/seed.sql','utf8'));});
afterAll(async()=>{await db?.close();});
describe('Actual PostgreSQL migrations, RLS and workflow',()=>{
 it('loads the DEMO fixture and distinguishes declared hours from VATH',async()=>{const s=await snapshot();expect(s.profile.full_name).toBe('Ana Martínez');expect(Number(s.experiences[0].hours)).toBe(32);expect(Number(s.experiences[0].verified_hours)).toBe(28);expect(s.credentials).toHaveLength(1);});
 it('enables RLS on every app table',async()=>{const r=await db.query<{relname:string;relrowsecurity:boolean}>("select relname,relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and relname<>'external_app'");expect(r.rows.length).toBe(15);expect(r.rows.every(x=>x.relrowsecurity)).toBe(true);});
 it('preserves unrelated tables and removes Supabase default anonymous function grants',async()=>{await expect(sql(null,'select * from external_app')).resolves.toEqual([]);await expect(sql(null,'select nexus_is_admin()')).rejects.toThrow();await expect(sql(null,'select * from student_skills')).rejects.toThrow();const rights=await db.query<{allowed:boolean}>("select has_function_privilege('anon','public.nexus_action(text,jsonb)','execute') as allowed");expect(rights.rows[0].allowed).toBe(false);});
 it('blocks rewriting final experiences and mismatching credential lineage',async()=>{await expect(db.query("update experiences set organization_id='20000000-0000-4000-8000-000000000002' where id='50000000-0000-4000-8000-000000000001'")).rejects.toThrow('immutable');await expect(db.query("update credentials set issuer_id='10000000-0000-4000-8000-000000000001' where id='60000000-0000-4000-8000-000000000001'")).rejects.toThrow('immutable');});
 it('blocks anonymous table reads and private RPCs',async()=>{await expect(sql(null,'select * from profiles')).rejects.toThrow();await expect(sql(null,'select nexus_snapshot()')).rejects.toThrow();await expect(sql(null,"select nexus_action('create_skill','{}')")).rejects.toThrow();});
 it('prevents direct role, state, audit and credential forgery',async()=>{for(const q of ["update profiles set role='admin'", "update experiences set status='verified'",'delete from credentials',"insert into activity_events(action) values('fake')"])await expect(sql(student,q)).rejects.toThrow();expect((await snapshot()).profile.role).toBe('student');});
 it('forces new Auth profiles to student even with hostile metadata',async()=>{await db.query("insert into auth.users(id,email,raw_user_meta_data) values('10000000-0000-4000-8000-000000000099','test@demo.invalid','{\"full_name\":\"Other User\",\"role\":\"admin\"}')");const s=await snapshot('10000000-0000-4000-8000-000000000099');expect(s.profile.role).toBe('student');expect(s.profile.is_public).toBe(false);expect(s.experiences).toHaveLength(0);expect(s.credentials).toHaveLength(0);});
 it('blocks privileged actions from a student',async()=>{for(const [name,payload] of [['create_organization',{name:'Intruder',type:'company'}],['create_skill',{name:'Fake',category:'technical'}],['set_member',{organization_id:org,user_id:student,role:'supervisor'}],['revoke_credential',{credential_id:'60000000-0000-4000-8000-000000000001',reason:'Forged'}]] as const)await expect(action(student,name,payload)).rejects.toThrow();});
 it('requires participation before creating challenge-linked experience and joins idempotently',async()=>{await expect(action(student,'create_experience',{...fixture,challenge_id:challenge})).rejects.toThrow();await action(student,'join_challenge',{challenge_id:challenge});await action(student,'join_challenge',{challenge_id:challenge});expect((await snapshot()).challenge_participants).toHaveLength(1);expect((await action(student,'create_experience',{...fixture,challenge_id:challenge})).id).toBeTruthy();});
 it('requires evidence and skills before submission',async()=>{const {id}=await action(student,'create_experience',fixture);await expect(action(student,'request_validation',{experience_id:id})).rejects.toThrow();});
 it('rejects self-validation and freezes submitted work',async()=>{const id=await makePending();await expect(action(student,'validate_experience',{experience_id:id,decision:'approve',rating:5,verified_hours:16,comment:'Fake approval'})).rejects.toThrow();await expect(action(student,'update_experience',{...fixture,id})).rejects.toThrow();await expect(action(student,'add_evidence',{experience_id:id,title:'Tamper',url:'https://example.com',kind:'url'})).rejects.toThrow();});
 it('rejects cross-organization reviewers and private reads',async()=>{await db.query("insert into organizations(id,name,type) values('20000000-0000-4000-8000-000000000099','Other company','company')");await action(admin,'set_member',{user_id:'10000000-0000-4000-8000-000000000099',organization_id:'20000000-0000-4000-8000-000000000099',role:'supervisor'});const id=await makePending();await expect(action('10000000-0000-4000-8000-000000000099','validate_experience',{experience_id:id,decision:'approve',rating:4,verified_hours:16,comment:'Other company'})).rejects.toThrow();expect((await snapshot('10000000-0000-4000-8000-000000000099')).evidence).toHaveLength(0);});
 it('atomically creates approval, skill levels, credential and audit; rejects repeat approval',async()=>{const id=await makePending();await expect(action(supervisor,'validate_experience',{experience_id:id,decision:'approve',rating:4,verified_hours:17,comment:'Too many hours'})).rejects.toThrow();const result=await action(supervisor,'validate_experience',{experience_id:id,decision:'approve',rating:4,verified_hours:12,comment:'Evidence reviewed'});const s=await snapshot();expect(s.experiences.find(e=>e.id===id)?.status).toBe('verified');expect(Number(s.experiences.find(e=>e.id===id)?.verified_hours)).toBe(12);expect(s.credentials.find(c=>c.id===result.id)?.status).toBe('active');expect(s.credential_skills.some(c=>c.credential_id===result.id&&c.level===4)).toBe(true);expect(s.activity_events.some(a=>a.action==='credential_created'&&a.entity_id===result.id)).toBe(true);await expect(action(supervisor,'validate_experience',{experience_id:id,decision:'approve',rating:4,verified_hours:12,comment:'Duplicate'})).rejects.toThrow();});
 it('supports changes, correction, resubmission and rejection without verified hours',async()=>{const id=await makePending();await action(supervisor,'validate_experience',{experience_id:id,decision:'request_changes',rating:2,verified_hours:0,comment:'Improve supporting evidence'});await action(student,'update_experience',{...fixture,id,title:'Experiencia corregida'});await action(student,'request_validation',{experience_id:id});await action(supervisor,'validate_experience',{experience_id:id,decision:'reject',rating:1,verified_hours:0,comment:'Insufficient evidence'});const s=await snapshot();expect(s.experiences.find(e=>e.id===id)?.status).toBe('rejected');expect(Number(s.experiences.find(e=>e.id===id)?.verified_hours)).toBe(0);expect(s.credentials.some(c=>c.experience_id===id)).toBe(false);});
 it('returns a minimal public record without emails, comments, private evidence, or audit',async()=>{const data=(await sql<{r:Snapshot}>(null,"select nexus_public_skillpass('ana-martinez-demo') as r"))[0].r;expect(data.profile.full_name).toBe('Ana Martínez');expect(data.evidence.some(e=>e.is_public===false)).toBe(false);expect(data.activity_events).toEqual([]);expect(data.validation_requests).toEqual([]);expect(JSON.stringify(data)).not.toContain('private-notes');expect(data.validations.every(v=>!v.comment)).toBe(true);expect(data.experiences.every(e=>['verified','revoked'].includes(String(e.status)))).toBe(true);});
 it('honors withdrawal of public consent immediately',async()=>{await action(student,'update_profile',{full_name:'Ana Martínez',is_public:false});expect((await sql<{r:unknown}>(null,"select nexus_public_credential('60000000-0000-4000-8000-000000000001') as r"))[0].r).toBeNull();await action(student,'update_profile',{full_name:'Ana Martínez',is_public:true});});
 it('revokes publicly and removes hours and skills from current claims',async()=>{const credential='60000000-0000-4000-8000-000000000001';await action(admin,'revoke_credential',{credential_id:credential,reason:'Fixture revoke test'});const publicData=(await sql<{r:Snapshot}>(null,'select nexus_public_credential($1::uuid) as r',[credential]))[0].r;expect(publicData.credential?.status).toBe('revoked');expect(publicData.experiences.find(e=>e.id==='50000000-0000-4000-8000-000000000001')?.status).toBe('revoked');const skills=await sql<{skill_id:string}>(student,'select * from student_skills');expect(skills.every(s=>s.skill_id===skill)).toBe(true);});
 it('institution can observe assigned students but not private evidence or reviews',async()=>{const s=await snapshot(DEMO_USERS.university);expect(s.experiences.length).toBeGreaterThan(0);expect(s.evidence).toHaveLength(0);expect(s.validations).toHaveLength(0);await expect(action(DEMO_USERS.university,'validate_experience',{experience_id:'50000000-0000-4000-8000-000000000001',decision:'approve',rating:5,verified_hours:20,comment:'Not allowed'})).rejects.toThrow();});
 it('academic observers still cannot read private artifacts when assigned to the company',async()=>{await action(admin,'set_member',{user_id:DEMO_USERS.university,organization_id:org,role:'university'});const s=await snapshot(DEMO_USERS.university);expect(s.experiences.length).toBeGreaterThan(0);expect(s.evidence).toHaveLength(0);expect(s.validations).toHaveLength(0);expect(s.validation_requests).toHaveLength(0);expect(s.activity_events.every(e=>e.actor_id===DEMO_USERS.university||e.subject_id===DEMO_USERS.university)).toBe(true);});
 it('returns null for unknown public UUIDs',async()=>{expect((await sql<{r:unknown}>(null,"select nexus_public_credential('00000000-0000-4000-8000-000000000001') as r"))[0].r).toBeNull();});
});
