project_id = "nexus-skillpass"

[db]
major_version = 17

[db.seed]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/auth/callback"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true
