"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { createContext, useContext, useEffect, useState, type ReactNode, type FormEvent } from "react";

export type Row = { id: string; [key: string]: string | number | boolean | null | undefined };
export type Profile = Row & { full_name: string; role: string; slug: string; is_public: boolean };
export type Snapshot = { profile: Profile; profiles: Profile[]; organizations: Row[]; organization_members: Row[]; skills: Row[]; challenges: Row[]; challenge_skills: Row[]; challenge_participants: Row[]; experiences: Row[]; experience_skills: Row[]; evidence: Row[]; validation_requests: Row[]; validations: Row[]; credentials: Row[]; credential_skills: Row[]; activity_events: Row[]; credential?: Row };
export type State = { mode: "demo" | "supabase"; snapshot: Snapshot; demoId?: string };
type WorkspaceContext = State & { reload: () => Promise<void>; run: (action: string, payload: Record<string, unknown>) => Promise<Record<string, unknown>> };
const Context = createContext<WorkspaceContext | null>(null);
export function useWorkspace() { const c = useContext(Context); if (!c) throw new Error("Workspace missing"); return c; }
export const labels: Record<string,string> = {student:"Estudiante",supervisor:"Validador",university:"Universidad",admin:"Administración",declared:"Declarada",pending_validation:"En revisión",changes_requested:"Cambios solicitados",rejected:"Rechazada",verified:"Verificada",revoked:"Revocada",technical:"Técnica",business:"Negocios",human:"Humana"};
export function value(row: Row | undefined, key: string, fallback = "") { return String(row?.[key] ?? fallback); }
export function named(rows: Row[] | undefined, id: unknown, fallback="Sin asignar") { return rows?.find(r=>r.id===id)?.name as string || fallback; }
export function badge(status: unknown) { const s=String(status ?? "declared"); return <span className={`badge badge-${s}`}>{labels[s] || s}</span>; }
export function shortDate(v: unknown) { if (!v) return "Sin fecha"; return new Intl.DateTimeFormat("es-MX",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(String(v))); }
export async function request<T>(url:string, options?:RequestInit):Promise<T> { const r=await fetch(url,{...options,headers:{"Content-Type":"application/json",...options?.headers}}); const data=await r.json(); if(!r.ok) throw new Error(data.error || "No se pudo completar la operación."); return data; }
export function publicHref(type:"skillpass"|"verify",id:string,demoId?:string) { return `/${type}/${encodeURIComponent(id)}${demoId?`?demo=${encodeURIComponent(demoId)}`:""}`; }
export function Brand(){return <Link href="/" className="brand" aria-label="AINDEV NEXUS inicio"><span className="brand-mark">N<span>↗</span></span><span>AINDEV <strong>NEXUS</strong><small>SKILLPASS · TALENTO APLICADO</small></span></Link>}
export function PublicHeader(){return <header className="public-header"><Brand/><nav><Link href="/demo">Explorar demo</Link><Link className="button button-dark button-small" href="/login">Iniciar sesión <span>↗</span></Link></nav></header>}
export function Footer(){return <footer className="footer"><Brand/><p>INVENTED, BUILT & SCALED FROM AGUASCALIENTES.</p><span>Experiencia que deja evidencia.</span></footer>}
export function Icon({kind}:{kind:string}) { const paths:Record<string,ReactNode>={dashboard:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,challenges:<><rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12h18M10 12v3h4v-3"/></>,profile:<><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>,review:<><path d="m8 12 3 3 6-7M5 3h14v18H5z"/></>,admin:<><circle cx="12" cy="12" r="8"/><path d="M12 8v8M8 12h8"/></>,pass:<><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 9h4M7 13h4M15 9h2v6h-2"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[kind] || paths.dashboard}</svg>}
export function Workspace({children}:{children:ReactNode}) {
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(""); const pathname=usePathname(),router=useRouter();
 async function reload(){ const next=await request<State>("/api/state"); setState(next); setError(""); }
 useEffect(()=>{let active=true; request<State>("/api/state").then(s=>{if(active)setState(s)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 async function run(action:string,payload:Record<string,unknown>){const response=await request<{result:Record<string,unknown>}>("/api/actions",{method:"POST",body:JSON.stringify({action,payload})});await reload();return response.result;}
 async function roleSwitch(role:string){try{setError("");await request("/api/auth",{method:"POST",body:JSON.stringify({intent:"demo",role})}); await reload();router.push("/dashboard");}catch(e){setError((e as Error).message)}}
 async function logout(){await request("/api/auth",{method:"POST",body:JSON.stringify({intent:"logout"})});router.push("/login");router.refresh();}
 if(!state)return <><PublicHeader/><main className="centered"><div className="card"><span className="eyebrow">NEXUS WORKSPACE</span><h1>{error?"Accede a tu espacio":"Preparando tu espacio…"}</h1>{error?<><p role="alert">{error}</p><Link href="/login" className="button button-dark">Iniciar sesión</Link><Link href="/demo" className="button button-outline">Usar demo</Link></>:<div className="loading-line"/>}</div></main></>;
 const {profile}=state.snapshot; const nav=[{href:"/dashboard",label:"Mi espacio",icon:"dashboard"},{href:"/challenges",label:"Retos reales",icon:"challenges"},{href:"/profile",label:"Mi perfil",icon:"profile"},...(profile.role!=="student"?[{href:"/review",label:profile.role==="university"?"Observatorio":"Validaciones",icon:"review"}]:[]),...(profile.role==="admin"?[{href:"/admin",label:"Administración",icon:"admin"}]:[])];
 return <Context.Provider value={{...state,reload,run}}><div className="app-shell"><aside className="sidebar"><Brand/><div className="nav-caption">TU CONOCIMIENTO, EN ACCIÓN</div><nav className="side-nav">{nav.map(n=><Link key={n.href} href={n.href} className={pathname.startsWith(n.href)?"active":""}><Icon kind={n.icon}/>{n.label}<span>↗</span></Link>)}</nav><div className="sidebar-bottom"><div className="network-note"><span className="live-dot"/> ALPHA NETWORK<p>El talento se demuestra.<br/>La evidencia lo conecta.</p></div><div className="user-summary"><div className="avatar">{profile.full_name?.split(" ").map(x=>x[0]).slice(0,2).join("") || "NX"}</div><div><strong>{profile.full_name}</strong><small>{labels[profile.role] || profile.role}</small></div><button className="icon-button" onClick={()=>logout().catch(e=>setError(e.message))} aria-label="Cerrar sesión">↪</button></div></div></aside><div className="workspace-main"><header className="workspace-top"><span>AINDEV NEXUS <span className="muted">/</span> <strong>SkillPass</strong></span><span className="top-location">AGUASCALIENTES, MX <span className="live-dot"/></span><button className="mobile-logout text-link" onClick={()=>logout().catch(e=>setError(e.message))}>Cerrar sesión</button></header>{state.mode==="demo"&&<div className="demo-banner"><strong>DEMO · DATOS FICTICIOS</strong><span>Entorno aislado para explorar el flujo completo.</span><select aria-label="Cambiar rol demo" value={profile.role} onChange={e=>roleSwitch(e.target.value)}>{["student","supervisor","university","admin"].map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></div>}{error&&<div className="error" role="alert">{error}</div>}<main className="workspace-content">{children}</main><div className="workspace-footer">AINDEV NEXUS · Evidencia antes que promesas.<span>ALPHA MVP / 2026</span></div></div></div></Context.Provider>
}
export function PageHeading({kicker,title,description,action}:{kicker:string,title:string,description?:string,action?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{kicker}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function Empty({title,text,action}:{title:string,text:string,action?:ReactNode}){return <div className="empty"><span className="empty-symbol">↗</span><h3>{title}</h3><p>{text}</p>{action}</div>}
export function Field({label,name,defaultValue="",type="text",required=false,placeholder,children,min,max,help}:{label:string,name:string,defaultValue?:string|number,type?:string,required?:boolean,placeholder?:string,children?:ReactNode,min?:number,max?:number,help?:string}){return <label className="field"><span>{label}{required&&<em> *</em>}</span>{children || (type==="textarea"?<textarea name={name} defaultValue={defaultValue} required={required} placeholder={placeholder} rows={4}/>:<input name={name} type={type} defaultValue={defaultValue} required={required} placeholder={placeholder} min={min} max={max}/>)}{help&&<small>{help}</small>}</label>}
export function ActionForm({action,children,payload,label="Guardar",success="Cambios guardados.",onDone,className=""}:{action:string,children:ReactNode,payload:(form:FormData)=>Record<string,unknown>,label?:string,success?:string,onDone?:(r:Record<string,unknown>)=>void,className?:string}){const {run}=useWorkspace();const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setMessage("");const form=e.currentTarget;try{const result=await run(action,payload(new FormData(form)));setMessage(success);onDone?.(result);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <form onSubmit={submit} className={`form ${className}`}>{children}{error&&<div role="alert" className="error">{error}</div>}{message&&<div role="status" className="success">{message}</div>}<div className="form-actions"><button disabled={busy} className="button button-dark" type="submit">{busy?"Procesando…":label}<span>↗</span></button></div></form>}
export function SkillsInput({selected=[]}:{selected?:string[]}){const {snapshot}=useWorkspace();return <fieldset className="skill-selector"><legend>Habilidades aplicadas <em>*</em></legend><div>{snapshot.skills.map(s=><label key={s.id}><input type="checkbox" name="skill_ids" value={s.id} defaultChecked={selected.includes(s.id)}/><span>{value(s,"name")}</span></label>)}</div><small>Selecciona al menos una. Se verifican únicamente tras la aprobación.</small></fieldset>}
export function Metric({label,number,note}:{label:string,number:string|number,note:string}){return <div className="metric"><span>{label}</span><strong>{number}</strong><small>{note}</small></div>}
