import { test,expect,type APIRequestContext } from '@playwright/test';
import { PNG } from 'pngjs';
import jsQR from 'jsqr';
const origin='http://127.0.0.1:3000';
const headers={Origin:origin};
async function demo(request:APIRequestContext,role='student'){const r=await request.post('/api/auth',{headers,data:{intent:'demo',role}});expect(r.ok(),await r.text()).toBe(true);return r.json();}
test('full student → challenge → evidence → supervisor → public SkillPass → QR → revoke',async({page,browser})=>{
 const consoleErrors:string[]=[];page.on('pageerror',e=>consoleErrors.push(e.message));
 await page.goto('/');await expect(page.getByRole('heading',{name:/Tu talento/})).toBeVisible();
 await page.screenshot({path:'artifacts/landing-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Explorar el MVP'}).click();
 await page.getByTestId('demo-role-student').click();
 await expect(page.getByRole('heading',{name:'Hola, Ana.'})).toBeVisible();
 await page.getByRole('link',{name:'Mi perfil'}).click();
 await page.getByLabel('Titular profesional').fill('Ingeniería aplicada · DEMO E2E');
 await page.getByRole('button',{name:'Guardar',exact:false}).click();await expect(page.getByRole('status')).toContainText('Cambios guardados');
 await page.getByRole('link',{name:'Retos reales'}).click();
 await page.getByRole('heading',{name:'Digital Transformation Challenge for SMEs'}).click();
 await page.getByRole('button',{name:'Participar en este reto'}).click();
 await page.getByRole('link',{name:'Registrar experiencia'}).click();
 await page.getByLabel('Actividad o proyecto').fill('Dashboard de ventas · E2E DEMO');
 await page.getByLabel('Descripción de la experiencia').fill('Analicé datos ficticios y construí un dashboard de ventas para esta prueba.');
 await page.getByLabel('Tu contribución y responsabilidades').fill('Mapeo de proceso y análisis de datos.');
 await page.getByLabel('Entregables', {exact:false}).fill('Reporte y dashboard de demostración.');
 await page.getByLabel('Fecha de inicio').fill('2026-09-01');await page.getByLabel('Fecha de término').fill('2026-09-20');
 await page.getByLabel('Horas declaradas').fill('16');
 await page.getByRole('button',{name:'Crear experiencia'}).click();
 await expect(page.getByRole('heading',{name:'Dashboard de ventas · E2E DEMO'})).toBeVisible();
 await page.getByLabel('Título de la evidencia').fill('Reporte público E2E');
 await page.getByLabel('Qué demuestra esta evidencia').fill('Evidencia de análisis para una demostración técnica.');
 await page.getByLabel('URL HTTPS').fill('https://example.com/e2e-report');
 await page.getByLabel('Publicar esta evidencia').check();
 await page.getByRole('button',{name:'Guardar evidencia'}).click();await expect(page.getByText('Reporte público E2E',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Solicitar validación'}).click();await expect(page.getByText('En espera del supervisor')).toBeVisible();
 await page.getByLabel('Cambiar rol demo').selectOption('supervisor');await expect(page.getByRole('heading',{name:'Experiencia que se puede comprobar.'})).toBeVisible();
 await page.getByRole('link',{name:'Validaciones',exact:false}).first().click();
 await page.getByRole('link',{name:/Dashboard de ventas · E2E DEMO/}).click();
 await page.getByLabel('Nivel demostrado').selectOption('4');
 await page.getByLabel('Horas que puedes verificar').fill('12');
 await page.getByLabel('Comentario profesional').fill('Revisé el reporte y confirmé el alcance de doce horas.');
 await page.getByRole('button',{name:'Registrar decisión'}).click();
 await page.getByRole('link',{name:'Ver credencial'}).click();
 await expect(page.getByRole('heading',{name:'Credencial verificada',exact:true})).toBeVisible();
 await expect(page.getByText('Supervisor Demo',{exact:true})).toBeVisible();
 await expect(page.getByText('12 VATH',{exact:true})).toBeVisible();
 const credentialUrl=page.url();
 const qr=page.getByAltText('QR que abre esta URL pública');await expect(qr).toBeVisible();
 const source=await qr.getAttribute('src');const png=PNG.sync.read(Buffer.from(source!.split(',')[1],'base64'));
 const decoded=jsQR(new Uint8ClampedArray(png.data),png.width,png.height);expect(decoded?.data).toBe(credentialUrl);
 await page.screenshot({path:'artifacts/credential-desktop.png',fullPage:true});
 const anonymous=await browser.newContext();const external=await anonymous.newPage();await external.goto(credentialUrl);await expect(external.getByRole('heading',{name:'Credencial verificada',exact:true})).toBeVisible();
 await external.getByRole('link',{name:'Ver SkillPass del titular'}).click();await expect(external.getByRole('heading',{name:'Ana Martínez',exact:true})).toBeVisible();
 await expect(external.getByText('Ingeniería aplicada · DEMO E2E',{exact:true})).toBeVisible();
 await expect(external.getByText('Notas privadas DEMO')).toHaveCount(0);
 await external.screenshot({path:'artifacts/skillpass-desktop.png',fullPage:true});
 await external.setViewportSize({width:390,height:844});await external.screenshot({path:'artifacts/skillpass-mobile.png',fullPage:true});
 expect(await external.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await anonymous.close();
 await demo(page.request,'admin');await page.goto('/admin');
 const record=page.locator('.credential-admin').filter({hasText:'Dashboard de ventas · E2E DEMO'});
 await record.getByText('Revocar credencial',{exact:true}).click();await record.getByLabel('Motivo de revocación').fill('Revocación de prueba de extremo a extremo.');
 await record.getByRole('button',{name:'Confirmar revocación'}).click();await expect(record.getByText('Revocada',{exact:true})).toBeVisible();
 await page.goto(credentialUrl);await expect(page.getByRole('heading',{name:'Credencial revocada',exact:true})).toBeVisible();await expect(page.getByText('0 VATH',{exact:true})).toBeVisible();
 expect(consoleErrors).toEqual([]);
});

test('private routes, honest missing Auth configuration, invalid public identifiers, CSRF',async({page,request})=>{
 await page.goto('/dashboard');await expect(page).toHaveURL(/\/login/);
 await page.getByLabel('Correo electrónico').fill('nobody@example.com');await page.getByLabel('Contraseña').fill('not-a-real-password');
 await page.getByRole('button',{name:'Iniciar sesión',exact:false}).click();await expect(page.getByRole('alert').filter({hasText:'Conecta Supabase'})).toBeVisible();
 const csrf=await request.post('/api/auth',{headers:{Origin:'https://malicious.example'},data:{intent:'demo',role:'admin'}});expect(csrf.status()).toBe(403);
 await page.goto('/verify/not-a-valid-uuid');await expect(page.getByText('INVALID / NO DISPONIBLE',{exact:true})).toBeVisible();
});

test('role and privacy protections through HTTP and session tampering',async({page,request,browser})=>{
 const {demoId}=await demo(request);const state=await (await request.get('/api/state')).json();
 const privilege=await request.post('/api/actions',{headers,data:{action:'create_skill',payload:{name:'Forged Skill',category:'technical'}}});expect(privilege.status()).toBe(403);
 const publicQuery=`/api/public?slug=${state.snapshot.profile.slug}&demo=${demoId}`;
 const publicData=await (await request.get(publicQuery)).json();expect(publicData.snapshot.evidence.every((e:{is_public:boolean})=>e.is_public)).toBe(true);
 await request.post('/api/actions',{headers,data:{action:'update_profile',payload:{full_name:'Ana Martínez',is_public:false}}});
 expect((await (await request.get(publicQuery)).json()).snapshot).toBeNull();
 const outsider=await browser.newContext();await outsider.addCookies([{name:'nexus_demo',value:demoId,domain:'127.0.0.1',path:'/'}]);const outsiderPage=await outsider.newPage();await outsiderPage.goto('/admin');await expect(outsiderPage).toHaveURL(/\/login/);await outsider.close();
 await page.goto('/demo');await expect(page.getByRole('button',{name:'Ver SkillPass'})).toBeVisible();
});
